apiVersion: v1
kind: Namespace
metadata:
  name: numalogic
---
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: numalogic-simple-pipeline
  namespace: numalogic
spec:
  watermark:
    disabled: true
  limits:
    readBatchSize: 10
    bufferMaxLength: 500
    bufferUsageLimit: 100
  vertices:
  - name: in
    source:
      http: {}
  - name: preprocess
    scale:
      min: 1
    udf:
      container:
        image: quay.io/numaio/numalogic/example-udf:v0.4
        env:
          - name: WIN_SIZE
            value: "12"
        args:
        - python
        - starter.py
        - preprocess
  - name: inference
    scale:
      min: 1
    udf:
      container:
        image: quay.io/numaio/numalogic/example-udf:v0.4
        env:
          - name: WIN_SIZE
            value: "12"
        args:
        - python
        - starter.py
        - inference
  - name: threshold
    scale:
      min: 1
    udf:
      container:
        image: quay.io/numaio/numalogic/example-udf:v0.4
        env:
          - name: WIN_SIZE
            value: "12"
        args:
          - python
          - starter.py
          - threshold
  - name: postprocess
    scale:
      min: 1
    udf:
      container:
        image: quay.io/numaio/numalogic/example-udf:v0.4
        env:
          - name: WIN_SIZE
            value: "12"
        args:
        - python
        - starter.py
        - postprocess
  - name: out
    scale:
      min: 1
    sink:
      log: {}
  - name: train
    scale:
      min: 1
    udf:
      container:
        env:
          - name: WIN_SIZE
            value: "12"
        image: quay.io/numaio/numalogic/example-udf:v0.4
        args:
          - python
          - starter.py
          - train
  edges:
    - from: in
      to: preprocess
    - from: preprocess
      to: inference
    - from: inference
      to: threshold
    - from: threshold
      to: train
      conditions:
        keyIn:
          - train
    - from: threshold
      to: postprocess
      conditions:
        keyIn:
          - postprocess
    - from: postprocess
      to: out

---
# redis deployment config
apiVersion: numaflow.numaproj.io/v1alpha1
kind: InterStepBufferService
metadata:
  name: redis-isbs
  namespace: numalogic
spec:
  redis:
    native:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: isbsvc
                  numaflow.numaproj.io/isbsvc-name: redis-isbs
              topologyKey: topology.kubernetes.io/zone
            weight: 100
      containerTemplate:
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 2
            memory: 1Gi
      persistence:
        accessMode: ReadWriteOnce
        volumeSize: 5Gi
      priorityClassName: numalogic-priority-class
      settings:
        redis: |
          min-replicas-to-write 1
          save ""
          appendonly yes
          auto-aof-rewrite-percentage 100
          auto-aof-rewrite-min-size 64mb
          maxmemory 4096mb
          maxmemory-policy allkeys-lru
      version: 7.0.15
