apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: numalogic-simple-pipeline
spec:
  watermark:
    disabled: true
  limits:
    readBatchSize: 10
    bufferMaxLength: 500
    bufferUsageLimit: 100
  vertices:
  - name: in
    source:
      generator:
        rpu: 5
        duration: 1s
  - name: preprocess
    udf:
      container:
        image: docker.io/library/numalogic-simple-pipeline:v1
        args:
        - python
        - starter.py
        - preprocess
  - name: input
    udf:
      container:
        image: docker.io/library/numalogic-simple-pipeline:v1
        args:
        - python
        - starter.py
        - input
  - name: inference
    udf:
      container:
        image: docker.io/library/numalogic-simple-pipeline:v1
        args:
        - python
        - starter.py
        - inference
    containerTemplate:
      env:
        - name: NUMAFLOW_DEBUG
          value: "true" # DO NOT forget the double quotes!!!
  - name: postprocess
    udf:
      container:
        image: docker.io/library/numalogic-simple-pipeline:v1
        args:
        - python
        - starter.py
        - postprocess
  - name: out
    sink:
      log: {}
  - name: out2
    sink:
      log: {}
  - name: out3
    sink:
      log: {}
  - name: train
    udf:
      container:
        env:
        - name: WIN_SIZE
          value: "12"
        image: docker.io/library/numalogic-simple-pipeline:v1
        args:
          - python
          - starter.py
          - train
  edges:
    - from: in
      to: out2
    - from: in
      to: input
    - from: input
      to: preprocess
    - from: inference
      to: train
      conditions:
        keyIn:
          - train
    - from: train
      to: out3
    - from: preprocess
      to: inference
    - from: inference
      to: postprocess
      conditions:
        keyIn:
          - postprocess
    - from: postprocess
      to: out