name: Generate release version

on:
  push:
    tags:
      - v*

jobs:
  generate_release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Generate changelog
      - run: git fetch --prune --prune-tags
      - run: git tag -l 'v*'
      - run: ./.hack/changelog.sh > ${{ github.workspace }}-_CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}-_CHANGELOG.txt